name: build docker image for frontend (react app)
on:
  push:
    branches: ["frontend"]
  pull_request:
    branches: ["frontend"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: print current dir
        run: pwd

      - name: Build the Docker image
        run: docker build frontend/ --tag alwaysbecalm/api_react:latest

      - name: login to docker hub
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u alwaysbecalm --password-stdin

      - name: push the image to docker hub
        run: docker push alwaysbecalm/api_react:latest

      - name: logout from docker hub
        run: docker logout
